fix!: single file database
hei-school/harena-api pull request #1
Opened 2024-08-07 14:11 UTC by kirisaki-vk

2024-08-12 07:54 UTC, hei-teacher requested changes

2024-08-12 07:54 UTC, hei-teacher commented on src/test/java/com/harena/api/service/PatrimoineServiceIT.java
> +        .thenReturn(Files.createTempFile("harena-tests", null).toFile());
use static import

2024-08-12 07:54 UTC, hei-teacher commented on src/main/java/com/harena/api/service/PatrimoineService.java
> +    } catch (Exception e) {
Preciser le type de l'exception qui correspond au NotFound. En particulier, pas TOUTES les exceptions sont des NotFound (eg: erreurs transcientes comme la perte de connection internet)

2024-08-12 07:54 UTC, hei-teacher commented on src/main/java/com/harena/api/service/PatrimoineService.java
> +      Path tempDir = Files.createTempDirectory("harena-api-toSavePatrimoines");
import static

2024-08-12 07:54 UTC, hei-teacher commented on src/main/java/com/harena/api/service/PatrimoineService.java
> +          String.format("Could not read values of patrimoine %s", patrimoineName));
Use String template

2024-08-12 07:54 UTC, hei-teacher commented on src/main/java/com/harena/api/service/PatrimoineService.java
> +      toSavePatrimoines.forEach((patrimoine) -> writeFile(tempDir, patrimoine));
superfluous ()

2024-08-12 07:54 UTC, hei-teacher commented on src/main/java/com/harena/api/service/PatrimoineService.java
> +      toSavePatrimoines.forEach((patrimoine) -> writeFile(tempDir, patrimoine));
Deep implications for the courageous ones: (1) partial application of function (2) curryfication

2024-08-12 07:54 UTC, hei-teacher commented on src/main/java/com/harena/api/service/PatrimoineService.java
> +    ListObjectsV2Request lsRequest =
var

2024-08-12 07:54 UTC, hei-teacher commented on src/main/java/com/harena/api/service/PatrimoineService.java
> +    int pageNumber = 1;
Increment it!

2024-08-12 07:54 UTC, hei-teacher commented on src/main/java/com/harena/api/service/PatrimoineService.java
> +    for (ListObjectsV2Response objects : lsIterable) {
Really not sure this is the proper way to do pagination in S3...

2024-08-12 07:54 UTC, hei-teacher commented on src/main/java/com/harena/api/service/PatrimoineService.java
> +                file -> {
superfluous {}

2024-08-12 07:54 UTC, hei-teacher commented on src/main/java/com/harena/api/service/PatrimoineService.java
> +                    String.format("Cannot read %s", file.getName()));
String template

2024-08-12 07:54 UTC, hei-teacher commented on src/main/java/com/harena/api/service/PatrimoineService.java
> +      Path filePath = Files.createFile(parentDir.resolve(StringNormalizer.apply(patrimoine.nom())));
static import

2024-08-12 07:54 UTC, hei-teacher commented on src/test/java/com/harena/api/service/PatrimoineServiceIT.java
> +    assertFalse(subject.getAllPatrimoine(PageRequest.of(1, 1)).isEmpty());
Page(1,1) is not representative of reality. People usually use something like Page(4,10)

2024-08-13 05:15 UTC, MiiJack commented on src/test/java/com/harena/api/service/PatrimoineServiceIT.java
> +        .thenReturn(Files.createTempFile("harena-tests", null).toFile());
Resolved

2024-08-29 08:29 UTC, merged